name: Debdist
description: Set debian distribution

inputs:
  dist:
    description: The distribution
    required: false
  distrev:
    description: Suffix for the version
    required: false

runs:
  using: docker
  image: docker://ghcr.io/fragoi/debuild:24.3
  entrypoint: set-dist.sh
  env:
    DEBDIST: ${{ inputs.dist }}
    DEBDISTREV: ${{ inputs.distrev }}
